-- Wellness activation schema patch (2026-07-13)
--
-- APPLY THIS TO PRODUCTION POSTGRES *BEFORE* THE BACKEND DEPLOYS.
-- Deploying the code first will break /admin — that is exactly what happened on July 5.
-- The prod DB is unreachable over Tailscale from WSL, so run this in the Coolify Postgres
-- terminal, then trigger the deploy.
--
-- Generated by diffing two real Postgres schemas built by Payload's own adapter (pre-wellness
-- commit af3977e vs current main), not hand-written — so it matches what Drizzle expects.
--
-- Safe to re-run: every statement is idempotent.
--
-- SAFETY NOTE: wellness_lifestyle and oils_incense have ZERO rows in production (verified via
-- the live API), so the NOT NULL columns below cannot fail on existing data. The
-- ADD-with-DEFAULT-then-DROP-DEFAULT dance keeps that true even if a row appears.

BEGIN;

-- 1. New enum for the top-level scentFamily select on wellness_lifestyle -------------------
DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'enum_wellness_lifestyle_scent_family') THEN
    -- Values and ORDER copied verbatim from the schema Payload's own adapter generates.
    -- Do not reorder or "tidy" these: Postgres enum ordering is part of the type's identity,
    -- and Drizzle compares against exactly this list.
    CREATE TYPE public.enum_wellness_lifestyle_scent_family AS ENUM (
      'floral', 'woody', 'citrus', 'herbal', 'spicy', 'earthy', 'sweet', 'fresh', 'exotic', 'sacred'
    );
  END IF;
END$$;

-- 2. wellness_lifestyle: top-level commerce + curation fields -------------------------------
ALTER TABLE wellness_lifestyle ADD COLUMN IF NOT EXISTS slug character varying;
ALTER TABLE wellness_lifestyle ADD COLUMN IF NOT EXISTS publish_online boolean DEFAULT false;
ALTER TABLE wellness_lifestyle ADD COLUMN IF NOT EXISTS hero_image_id integer;
ALTER TABLE wellness_lifestyle ADD COLUMN IF NOT EXISTS scent_family public.enum_wellness_lifestyle_scent_family;

-- Relaxed: the importer cannot supply this, and it is no longer required.
ALTER TABLE wellness_lifestyle ALTER COLUMN primary_ingredient DROP NOT NULL;

-- 3. oils_incense: top-level commerce + curation fields -------------------------------------
ALTER TABLE oils_incense ADD COLUMN IF NOT EXISTS slug character varying;
ALTER TABLE oils_incense ADD COLUMN IF NOT EXISTS publish_online boolean DEFAULT false;
ALTER TABLE oils_incense ADD COLUMN IF NOT EXISTS hero_image_id integer;

-- Relaxed: scent is now a VARIANT axis (one "Scented Oil" product, 104 scent variations),
-- so there is no single base scent at the product level.
ALTER TABLE oils_incense ALTER COLUMN base_scent DROP NOT NULL;

-- 4. wellness_lifestyle_variations: price / stock / weight / variantName ---------------------
ALTER TABLE wellness_lifestyle_variations ADD COLUMN IF NOT EXISTS variant_name character varying;
ALTER TABLE wellness_lifestyle_variations ADD COLUMN IF NOT EXISTS price numeric NOT NULL DEFAULT 0;
ALTER TABLE wellness_lifestyle_variations ALTER COLUMN price DROP DEFAULT;
ALTER TABLE wellness_lifestyle_variations ADD COLUMN IF NOT EXISTS stock numeric DEFAULT 0;
ALTER TABLE wellness_lifestyle_variations ADD COLUMN IF NOT EXISTS weight numeric;
ALTER TABLE wellness_lifestyle_variations DROP COLUMN IF EXISTS medusa_variant_id;

-- 5. oils_incense_variations: scent / variantName / price / stock / weight -------------------
ALTER TABLE oils_incense_variations ADD COLUMN IF NOT EXISTS scent character varying;
ALTER TABLE oils_incense_variations ADD COLUMN IF NOT EXISTS variant_name character varying;
ALTER TABLE oils_incense_variations ADD COLUMN IF NOT EXISTS price numeric NOT NULL DEFAULT 0;
ALTER TABLE oils_incense_variations ALTER COLUMN price DROP DEFAULT;
ALTER TABLE oils_incense_variations ADD COLUMN IF NOT EXISTS stock numeric DEFAULT 0;
ALTER TABLE oils_incense_variations ADD COLUMN IF NOT EXISTS weight numeric;
ALTER TABLE oils_incense_variations DROP COLUMN IF EXISTS medusa_variant_id;

-- Relaxed: size is not inferable from Square, and most oils are a uniform bottle.
ALTER TABLE oils_incense_variations ALTER COLUMN size DROP NOT NULL;

-- 6. Drop the de-duplicated nested scentProfile.scentFamily ----------------------------------
-- It duplicated the new top-level scent_family. Zero rows in prod, so nothing is lost.
DROP TABLE IF EXISTS wellness_lifestyle_scent_profile_scent_family;
DROP TYPE  IF EXISTS enum_wellness_lifestyle_scent_profile_scent_family;

-- 7. Foreign keys for the new heroImage uploads ---------------------------------------------
DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'wellness_lifestyle_hero_image_id_media_id_fk') THEN
    ALTER TABLE public.wellness_lifestyle
      ADD CONSTRAINT wellness_lifestyle_hero_image_id_media_id_fk
      FOREIGN KEY (hero_image_id) REFERENCES public.media(id) ON DELETE SET NULL;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'oils_incense_hero_image_id_media_id_fk') THEN
    ALTER TABLE public.oils_incense
      ADD CONSTRAINT oils_incense_hero_image_id_media_id_fk
      FOREIGN KEY (hero_image_id) REFERENCES public.media(id) ON DELETE SET NULL;
  END IF;
END$$;

-- 8. Indexes ---------------------------------------------------------------------------------
CREATE UNIQUE INDEX IF NOT EXISTS wellness_lifestyle_slug_idx           ON public.wellness_lifestyle USING btree (slug);
CREATE INDEX        IF NOT EXISTS wellness_lifestyle_publish_online_idx ON public.wellness_lifestyle USING btree (publish_online);
CREATE INDEX        IF NOT EXISTS wellness_lifestyle_hero_image_idx     ON public.wellness_lifestyle USING btree (hero_image_id);

CREATE UNIQUE INDEX IF NOT EXISTS oils_incense_slug_idx                 ON public.oils_incense USING btree (slug);
CREATE INDEX        IF NOT EXISTS oils_incense_publish_online_idx       ON public.oils_incense USING btree (publish_online);
CREATE INDEX        IF NOT EXISTS oils_incense_hero_image_idx           ON public.oils_incense USING btree (hero_image_id);

CREATE INDEX IF NOT EXISTS wellness_lifestyle_scent_profile_scent_notes_order_idx
  ON public.wellness_lifestyle_scent_profile_scent_notes USING btree (_order);
CREATE INDEX IF NOT EXISTS wellness_lifestyle_scent_profile_scent_notes_parent_id_idx
  ON public.wellness_lifestyle_scent_profile_scent_notes USING btree (_parent_id);

COMMIT;

-- Verify (should return 0 rows — i.e. nothing missing):
--
--   SELECT c.expected FROM (VALUES
--     ('wellness_lifestyle','slug'), ('wellness_lifestyle','publish_online'),
--     ('wellness_lifestyle','hero_image_id'), ('wellness_lifestyle','scent_family'),
--     ('oils_incense','slug'), ('oils_incense','publish_online'), ('oils_incense','hero_image_id'),
--     ('wellness_lifestyle_variations','price'), ('wellness_lifestyle_variations','stock'),
--     ('wellness_lifestyle_variations','weight'), ('wellness_lifestyle_variations','variant_name'),
--     ('oils_incense_variations','price'), ('oils_incense_variations','stock'),
--     ('oils_incense_variations','weight'), ('oils_incense_variations','variant_name'),
--     ('oils_incense_variations','scent')
--   ) AS c(tbl, expected)
--   WHERE NOT EXISTS (
--     SELECT 1 FROM information_schema.columns
--     WHERE table_name = c.tbl AND column_name = c.expected
--   );
